### ISSUE TITLE
Doesn't show main text area

### ISSUE THREAD

**Issue by yutzhead** [oskusalerma/trelby#365]
![Image of Yaktocat](http://i.imgur.com/fAPfuo4.png)

Shouldn't there be a text area where the gray background is?

**Comment by anilgulecha** [comment]
Yes. Have you pulled the latest code? Looks like it could be to do with the wx3.0 version. Can you run trelby from the console, and post any errors you see here.

**Comment by yutzhead** [comment]
$ python bin/trelby
    05:43:06: Debug: Adding duplicate image handler for 'PNG file'
    05:43:06: Debug: Adding duplicate image handler for 'JPEG file'

That's all she wrote.

**Comment by yutzhead** [comment]
Here are some more:
```
(trelby:14509): Gtk-WARNING **: drawing failure for widget `wxPizza': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `wxPizza': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkWindow': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `wxPizza': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `wxPizza': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkWindow': invalid matrix (not invertible)
(pdf:14516): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
(trelby:14509): GLib-GObject-WARNING **: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
(trelby:14509): GLib-GObject-WARNING **: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
(trelby:14509): GLib-GObject-WARNING **: The property GtkAlignment:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
(trelby:14509): GLib-GObject-WARNING **: The property GtkAlignment:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
Traceback (most recent call last):
  File "src/trelby.py", line 2563, in OnToolBarMenu
    self.PopupMenu(menu)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 11144, in PopupMenu
    return _core_.Window_PopupMenu(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "!IsAttached()" failed at ./src/common/menucmn.cpp(715) in SetInvokingWindow(): menus attached to menu bar can't have invoking window
gvfs-open: file:///opt/trelby/manual.html: error opening location: Error when getting information for file '/opt/trelby/manual.html': No such file or directory
(pdf:14549): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
(trelby:14509): Gtk-WARNING **: drawing failure for widget `wxPizza': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `wxPizza': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkWindow': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `wxPizza': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `wxPizza': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(trelby:14509): Gtk-WARNING **: drawing failure for widget `GtkWindow': invalid matrix (not invertible)
```

**Comment by yutzhead** [comment]
The pizza box thing happens upon resizing the window, btw.

**Comment by yutzhead** [comment]
![Yoctocat](http://i.imgur.com/OvIlYgM.png)

Getting closer...

**Comment by thisgeekza** [comment]
For what it's worth, Trelby works correctly in a fresh install of Ubuntu 15.04.

**Comment by yutzhead** [comment]
So does Final Draft on a Mac, but that doesn't explain why the text area has a width of 1px. :)

**Comment by oskusalerma** [comment]
I installed Fedora 22 in a virtual machine and was able to reproduce this problem. Other problems as well: going fullscreen and exiting fullscreen leaves the window completely empty, i.e. toolbar and menubar disappear.

Obviously something going very wrong somewhere. Will try to figure out what, but if somebody beats me to it, I'll gladly accept patches.

**Comment by yutzhead** [comment]
I have some new insight on this from running Scrupoulous, which is ported to python3:
```
Traceback (most recent call last):
  File "src/trelby.py", line 2560, in OnCursorTimer
    self.panel.ctrl.DrawCursor(self.blinkState)
  File "src/trelby.py", line 345, in DrawCursor
    dc = wx.PaintDC(self)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_gdi.py", line 5130, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "IsOk()" failed at ./src/common/dcgraph.cpp(437) in SetTextBackground(): wxGCDC(cg)::SetTextBackground - invalid DC
```

**Comment by oskusalerma** [comment]
What's Scrupoulous? Google doesn't find anything for that term.

Anyway, python3 is irrelevant, Fedora22 is not using python3.

**Comment by oskusalerma** [comment]
I think this is a GTK3 issue. Debian jessie, where things work:

$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
>>> import wx
>>> wx.version()
'3.0.1.1 gtk2 (classic)'

Fedora 22, where things don't work:

$ python
Python 2.7.10 (default, Jul 5 2015, 14:15:43)
>>> import wx
>>> wx.version()
>>> '3.0.2.0 gtk3 (classic)'

**Comment by yutzhead** [comment]
https://github.com/millingjon/scrupulous
A fork of Trelby that happens to be ported to Python 3, but experiences the exact same problems.

Hopefully http://wiki.wxpython.org/ProjectPhoenix will fix it.

**Comment by yutzhead** [comment]
Same on Fedora 23 Beta still.
